CONTAINER fxp_sampleeffector
{
	NAME	fxp_sampleeffector;
	INCLUDE Obaseeffector;

	GROUP	ID_MG_BASEEFFECTOR_GROUPEFFECTOR
	{
		GROUP
		{
			COLUMNS 2;
			LINK SEFF_CHANNEL { ACCEPT{fx_channel_base; }}
			BUTTON SEFF_CHANNEL_SELECTOR {}
		}
		
		SEPARATOR {LINE;}

		LONG SEFF_WEIGHT_TARGET
		{
			CYCLE
			{
				SEFF_WEIGHT_TARGET_ALL;
				SEFF_WEIGHT_TARGET_POS;
				SEFF_WEIGHT_TARGET_ROT;
				SEFF_WEIGHT_TARGET_SCALE;
				SEFF_WEIGHT_TARGET_COLOROPACITY;
				SEFF_WEIGHT_TARGET_VISIBILITY;
				SEFF_WEIGHT_TARGET_WEIGHT;				
				SEFF_WEIGHT_TARGET_INDEX;
				SEFF_WEIGHT_TARGET_TIME;
			}
		}
		REAL SEFF_SCALE { UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
	}
}
