#ifndef fxp_sampleeffector_H__
#define fxp_sampleeffector_H__

enum
{
	SEFF_SCALE	=	1500,
	SEFF_CHANNEL,
	SEFF_CHANNEL_SELECTOR,
	SEFF_WEIGHT_TARGET = 1503,
		SEFF_WEIGHT_TARGET_ALL = 0,
		SEFF_WEIGHT_TARGET_POS,
		SEFF_WEIGHT_TARGET_ROT,
		SEFF_WEIGHT_TARGET_SCALE,
		SEFF_WEIGHT_TARGET_COLOROPACITY,
		SEFF_WEIGHT_TARGET_VISIBILITY,
		SEFF_WEIGHT_TARGET_WEIGHT,			
		SEFF_WEIGHT_TARGET_INDEX,
		SEFF_WEIGHT_TARGET_TIME
};
#endif 
