#ifndef FX_PROPERTY_H
#define FX_PROPERTY_H

enum ParticleProperty
{
	PROPERTY_TYPE = 2001,
		PROPERTY_TYPE_RADIUS = 0,
		PROPERTY_TYPE_BIRTH,
		PROPERTY_TYPE_AGE,
		PROPERTY_TYPE_DENSITY,
		PROPERTY_TYPE_VISCOSITY,
		PROPERTY_TYPE_PRESSURE,
		PROPERTY_TYPE_TEMPERATURE,
		PROPERTY_TYPE_FIRE,
		PROPERTY_TYPE_FUEL,
		PROPERTY_TYPE_MASS,
		PROPERTY_TYPE_ISODENSITY,
		PROPERTY_TYPE_ANISOTROPY = 12,
		PROPERTY_TYPE_CURVATURE,

		PROPERTY_TYPE_COLOR = 25,
		PROPERTY_TYPE_WEIGHTEDPOS = 29,
		PROPERTY_TYPE_NORMAL = 34,
		PROPERTY_TYPE_TENSION,
		PROPERTY_TYPE_POSITION_OLD,
		PROPERTY_TYPE_VELOCITY,
		PROPERTY_TYPE_VORTICITY,
		PROPERTY_TYPE_BALLISTIC_FORCE,
		PROPERTY_TYPE_POSITION,
		PROPERTY_TYPE_POSITION_OLDFRAME,
		PROPERTY_TYPE_UVW = 45,
		PROPERTY_TYPE_POSITION_DEFORMED = 48,

		PROPERTY_TYPE_STATE = 50,
				
		PROPERTY_TYPE_CUSTOM = 75,
		PROPERTY_TYPE_CUSTOMVECTOR,
		PROPERTY_TYPE_CUSTOMSTATE,

		PROPERTY_TYPE_ANY = 200

};

#endif